CREATE DATABASE Notlar;
USE Notlar;
CREATE TABLE NotlarUser (
	ID INT NOT NULL AUTO_INCREMENT,
	Username VARCHAR(255) NOT NULL UNIQUE,
    UserPassword VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
CREATE TABLE UserNotes (
	ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(255),
    Note LONGTEXT,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES NotlarUser(ID)
);
